### ISSUE TITLE
SoccerWindow2 doesn't works well on Ubuntu

### ISSUE THREAD

**Issue by tsa3** [herodrigues/robocup2d-tutorial#12]
Hello, I was using soccerwindow2 on PopOS and everything works well, but when I change to Ubuntu and after install all tools soccerwindow2 didn't works well, when I started a game or a log gamer the teams the position of the players still in the center and nothing happened. I will send you a screenshot to the soccerwindow2 that show what happened after start a match. 
Thanks mate
![problensSoccerWindow2](https://user-images.githubusercontent.com/42845662/68355619-93328700-00ee-11ea-96b2-e61bd275f80b.png)

**Comment by rug** [comment]
Since in your case SoccerWindow2 seems not to crash but only to misintepret the positions, this may be due to the fact that your locale Format uses commas instead of points to represent textually floating point numbers (or may be any other locale format misunderstanding). You have to set the locale formats of your operating system as "United States". Try the following:
1) Go to the "Settings" section of your Ubuntu installation.
Depending on the version of Ubuntu you are running, you may go there either clicking on the 9 dots on the bottom left of the desktop ("show applications") and then searching for "settings" and selecting that app (it should have a gear and a wrench in the icon), or you can click a small triangle on the top right of your desktop and then on the menu select the round icon with a screwdriver and a wrench inside, or in some other version on the top right of the desktop you have a gear icon and clicking on it a menu pops-up in which you can select the voice "system settings".  
2) once in settings, select "Region & Language" on the left column, then in the "Formats" field you should choose "United States".

Hopefully that should be enough.

**Comment by herodrigues** [comment]
@tsa3 I assume you're Brazilian and you're probably using Ubuntu in Portuguese, which uses comma as decimal separator.

@rug's solution should work fine.

Also, this is stated in the README file:
> It is preferable to use your Linux distribution in English. Some problems were reported when executing the simulator when the system language uses comma as decimal separator.

**Comment by tsa3** [comment]
Soccerwindow is working now, thanks guys.
