### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by MaycolTeles** [herodrigues/robocup2d-tutorial#13]
Hi @herodrigues! First of all, I wanna thank you for all the effort, help and support with this guide! It helped me a lot!

However, I got really upset when I finished the guide, following the sequence with my own code (which was awesome, by the way), and saw that there are some missing files/sections. I'm marking this as a issue, but I don't know if you're actually planning to finish it.
In case you don't want to finish, I would like to know if you could indicate other excellent materials like this one.
Thanks!

**Comment by herodrigues** [comment]
Hi @MaycolTeles 

I do not have plans to finish it. I created this repo back at university when I was part of a simulation 2D team and I couldn't find enough material to get started.
The only complete sections are those related to installation and configuration.

The official tutorial for the **agent2D** and **librcsc** is written in Japanese.
I had plans to translate all of them from Japanese to English, but agent2D is just a base team and there's no new version since 2012.
By the way, you can use other base teams such as [wrighteagle](https://github.com/wrighteagle2d/wrighteaglebase).

You can also find the official manual for the **server** at https://rcsoccersim.github.io/manual/

Thanks for pointing that out. I'm gonna put a warning about that in the README file.
